name: Register Model in Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register_model:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Register the model in Azure ML
      - name: Register Model
        run: |
          az ml model create --name trained-model \
            --path Out/trained_model.pkl \
            --description "Trained model for MLOPS project" \
            --tags "stage=production" \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }}
