name: Register Model in Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_register_model:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Training Script
      - name: Train the Model
        run: |
          python scripts/train_model.py \
          --trainingdata azMLOPS/Out/preprocessed_data.csv \
          --outputmodel azMLOPS/Out/trained_model.pkl

      # Step 5: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Register the Model
      - name: Register Model
        run: |
          az ml model create \
            --name trained-model \
            --path azMLOPS/Out/trained_model.pkl \
            --description "Trained model for azMLOPS project" \
            --tags "stage=production" \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }}
